import test from "node:test";
import assert from "node:assert/strict";
import {detectDynamicSvgBlocks,runAudit} from "../tools/audit-dynamic-visuals.mjs";

test("0-19 dynamic visualization audit covers every numbered module",()=>{const{manifest,visualRows,summary}=runAudit();assert.equal(manifest.modules.length,20);assert.deepEqual(manifest.modules.map(x=>x.module).sort((a,b)=>a-b),Array.from({length:20},(_,i)=>i));assert.equal(summary.modules,20);assert.ok(visualRows.length>0);assert.ok(Number.isInteger(summary.dynamicSvgs));for(const m of manifest.modules)for(const f of["model","validRegion","knownBoundary","action"])assert.ok(String(m[f]).length>0,`M${m.module} ${f}`)});
test("every interactive numbered HTML file inherits an explicit fidelity policy",()=>{const{manifest,visualRows}=runAudit(),policies=new Map(manifest.modules.map(x=>[x.module,x]));for(const row of visualRows){assert.ok(policies.has(row.module),row.path);assert.equal(row.fidelity,policies.get(row.module).defaultFidelity,row.path);assert.ok(row.canvases+row.ranges+row.selects+row.dynamicSvgs>0,row.path)}});
test("JS-mutated SVGs are audited while decorative static SVGs are ignored",()=>{const html='<svg id="logo"><path id="mark"/></svg><svg id="plot"><path id="curve"/></svg>',script='const mark=document.getElementById("mark"); console.log(mark); const curve=document.getElementById("curve"); curve.setAttribute("d", nextPath);';assert.deepEqual(detectDynamicSvgBlocks(html,script).map(x=>x.id),["plot"])});
test("selector-chain SVG mutation is detected without slider or canvas",()=>{assert.deepEqual(detectDynamicSvgBlocks('<svg id="scope"><polyline id="trace"/></svg>','document.querySelector("#scope #trace").setAttribute("points", samples);').map(x=>x.id),["scope"])});
test("Module 17 canvases are owned by model-contract single source",()=>{const{modelContracts,visualRows}=runAudit(),declared=new Map(modelContracts.visuals.filter(v=>v.module===17).map(v=>[v.id,v])),actual=new Set(visualRows.filter(x=>x.module===17).flatMap(x=>x.canvasIds));assert.deepEqual([...actual].sort(),[...declared.keys()].sort());assert.equal(declared.size,7);for(const[id,v]of declared){assert.equal(v.fidelity,"EQUATION_GRADE",id);for(const f of["units","equation","validRegion","knownBoundary"])assert.ok(String(v[f]).trim(),`${id} ${f}`);assert.ok(v.boundaryTests.length>0,id)}});
test("Module 18 is explicitly mixed after equation-backed workbench is added",()=>{const{manifest}=runAudit(),m=manifest.modules.find(x=>x.module===18);assert.equal(m.defaultFidelity,"MIXED");assert.match(m.model,/workbench/i);assert.match(m.knownBoundary,/provenance/i)});
